version: 0.2

# true - means that the plugin whitelist is enabled
# false - means that the plugin whitelist is disabled
enable: false


# You can choose which database to use from the plugin or your own.
# enable: false - means that the plugin will use its database created in the plugin folder
# enable: true - means that the plugin will connect to your database, the connection parameters to which you specify below
database:
  enable: false
  host: "hostname"
  port: 3600
  database_name: "database_name"
  username: "username"
  password: "password"

# Create a bot on the discord developer portal and paste its token
# https://discord.com/developers/applications
discordBot:
  enabled: false
  token: "YOUR TOKEN"
  # Activity: "WATCHING", "PLAYING", "NOTHING"
  # "NOTHING" - does not output anything
  activity: "WATCHING"
  # {online} displays online on the server
  activityText: "{online}"

# The variable {nickname} is replaced with the nickname of the player to whom the discord is linked,
# otherwise it is replaced with "unknown".
discordBotEmbeds:
  info:
    color: "#B2FF02" # HEX color only
    title: "Server information"
    description:
      - "Nickname: {nickname}"
      - ""
      - "Version: your minecraft server version"
      - "IP: your.server.ip"
  play:
    color: "#B2FF02" # HEX color only
    title: "Success"
    description:
      - "You have been successfully added to the whitelist."
  code:
    color: "#B2FF02" # HEX color only
    title: "Success"
    description:
      - "Nickname successfully linked."
  errors:
    discordAlreadyExists:
      color: "#FF0000" # HEX color only
      title: "Error"
      description:
        - "You already have a linked Minecraft nickname."
    nicknameAlreadyExists:
      color: "#FF0000" # HEX color only
      title: "Error"
      description:
        - "The specified nickname is taken."
    codeNotExists:
      color: "#FF0000" # HEX color only
      title: "Error"
      description:
        - "The specified code is not in the database."
    nicknameAlreadyLinked:
      color: "#FF0000" # HEX color only
      title: "Error"
      description:
        - "The nickname that this code belongs to is already linked to Discord."


messages:
  ErrorMessages:
    NoPerm: "&cYou do not have the permission to use this command"
    PlayerAlready: "&cThis player is already on the whitelist"
    PlayerNotSpec: "&cYou haven't specified a player"
    NoPlayer: "&cThe specified player was not found"
    DiscordNotSpec: "&cYou did not provide a Discord ID"
    NoDiscord: "&cThis Discord ID is not in the database"
    NewNickNotSpec: "&cYou did not specify a new player nickname"
    NotWhitelist: "&cYou are not whitelisted on this server!"

  code:
    sucOwnCode: "&aYour code: "
    sucOtherCode: "&a%p code: "  # %p is the nickname of the player whose code you want to receive. (It only works here)

  qwhitelist:
    sucRemove: "&aThe player has been successfully removed from the white list"
    sucAdd: "&aThe player has been successfully added to the whitelist"
    sucUpdate: "&aNickname successfully changed"
    sucReload: "&aConfig has been successfully updated"
